name: Build and upload python packages

on:
  create:
    tags:
      - v*

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'macos-10.15']
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-20.04'
      run: sudo make apt-install-deps
      env:
        DEBIAN_FRONTEND: noninteractive

    - name: Install dependencies (OSX)
      if: matrix.os == 'macos-10.15'
      run: make brew-install-deps

    - name: Build python wheel
      run: |
        make download-pybind11
        python3 -m pip install setuptools wheel twine
        python3 setup.py build_ext bdist_wheel
      env:
        CXX: clang++

    - name: Save wheel as artifact
      uses: actions/upload-artifact@v1
      with:
        name: mosestokenizer-${{matrix.python-version}}-${{matrix.os}}
        path: dist/

    - name: Upload to PyPI
      run: twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
