name: Build and upload linux x86_64 python packages

on:
  create:
    tags:
      - v*
  push:
    branches:
      - master

jobs:
  release-pypi:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build package and upload from docker
      run: docker run --rm -v "${PWD}:/opt/fast-mosestokenizer" \
        ubuntu:16.04 /bin/bash /opt/fast-mosestokenizer/build-release-linux.sh
