name: Build and upload python packages

on:
  create:
    tags:
      - v*

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'macos-10.15']
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-20.04'
      run: sudo make apt-install-deps
      env:
        DEBIAN_FRONTEND: noninteractive

    - name: Install dependencies (OSX)
      if: matrix.os == 'macos-10.15'
      run: make brew-install-deps

    - name: Build python wheel (Linux)
      if: matrix.os == 'ubuntu-20.04'
      run: |
        make download-pybind11
        python -m pip install setuptools wheel twine
        python setup.py build_ext bdist_wheel --plat-name manylinux1_x86_64
      env:
        CXX: clang++

    - name: Build python wheel (OSX)
      if: matrix.os == 'macos-10.15'
      run: |
        make download-pybind11
        python -m pip install setuptools wheel twine
        python setup.py build_ext bdist_wheel
      env:
        CXX: clang++

    - name: Upload to PyPI
      run: python -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
